language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.3
services:
  - postgresql
env:
  - DATABASE_URL='postgres://localhost/posgres'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - bundle exec hanami db prepare
