version: '2'
services:
  web:
    build: .
    command: hanami server --host=0.0.0.0
    volumes:
      - .:/bookshelf
    ports:
      - '2300:2300'
    depends_on:
      - db
    volumes_from:
      - bundle
  db:
    image: postgres
  bundle:
    image: bookshelf_web
    volumes:
      - /bundle
