version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: hanami server --host=0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - '2300:2300'
    links:
      - db
    volumes_from:
      - bundle
  bundle:
    image: bookshelf_web
    volumes:
      - /bundle
