version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ['bundle', 'exec', 'hanami', 'server']
    volumes:
      - .:/myapp
    ports:
      - '2300:2300'
    depends_on:
      - db
